apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
  namespace: kedademo
spec:
  replicas: 0
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
      - name: consumer
        image: techsoumen/consumer:latest
        envFrom:
        - secretRef:
            name: aws-secrets
